# Generated by Django 4.2.5 on 2023-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_smartphone_og_price_alter_smartphone_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphone',
            name='og_price',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='headphone',
            name='price',
            field=models.IntegerField(default=900),
        ),
    ]
