# Generated by Django 4.2.5 on 2023-09-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
