# Generated by Django 4.2.5 on 2023-09-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_computer_weight_alter_computer_has_monitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='instocks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='is_onsale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='is_recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computer',
            name='og_price',
            field=models.IntegerField(default=22000),
        ),
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.IntegerField(default=19900),
        ),
    ]
