# Generated by Django 4.2.5 on 2023-09-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_cloth_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='headphone',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Cloth',
        ),
        migrations.DeleteModel(
            name='Computer',
        ),
        migrations.DeleteModel(
            name='Headphone',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
