# Generated by Django 4.2.5 on 2023-09-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_instock', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('is_laptop', models.BooleanField(default=False)),
                ('is_gamingtype', models.BooleanField(default=False)),
                ('has_monitor', models.BooleanField(default=False)),
                ('cpu', models.CharField(max_length=100)),
                ('cpu_brand', models.CharField(choices=[('RedA', 'Reda'), ('BlueI', 'Bluei')], max_length=10)),
                ('ram', models.CharField(choices=[('4Gb', '4Gb'), ('8Gb', '8Gb'), ('16Gb', '16Gb'), ('32Gb', '32Gb'), ('64Gb', '64Gb')], max_length=10)),
                ('gpu', models.CharField(max_length=100)),
                ('gpu_brand', models.CharField(choices=[('RedA', 'Reda'), ('BlueI', 'Bluei'), ('GreenN', 'Greenn')], max_length=10)),
                ('storage', models.CharField(max_length=10)),
                ('storage_type', models.CharField(choices=[('HDD', 'Hdd'), ('SSD', 'Ssd')], max_length=10)),
                ('size', models.CharField(choices=[('14"', '14"'), ('15.6"', '15.6"'), ('16"', '16"'), ('24"', '24"'), ('27"', '27"'), ('32"', '32"')], max_length=10)),
                ('case', models.CharField(choices=[('mini-ITX', 'Mini-Itx'), ('micro-ATX', 'Micro-Atx'), ('ATX', 'Atx')], max_length=10)),
                ('resolution', models.CharField(choices=[('768p', '768P'), ('1080p', '1080P'), ('1440p', '1440P'), ('4K', '4K')], max_length=10)),
                ('refreshrate', models.CharField(choices=[('60hz', '60Hz'), ('75hz', '75Hz'), ('90hz', '90Hz'), ('120hz', '120Hz'), ('144hz', '144Hz'), ('240hz', '240Hz')], max_length=10)),
                ('display', models.CharField(choices=[('IPS', 'Ips'), ('TN', 'Tn'), ('VA', 'Va'), ('OLED', 'Oled')], max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
            ],
        ),
    ]
