# Generated by Django 4.2.5 on 2023-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_image_computer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='weight',
            field=models.FloatField(default=1.7),
        ),
        migrations.AlterField(
            model_name='computer',
            name='has_monitor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.IntegerField(default=20000),
        ),
        migrations.AlterField(
            model_name='computer',
            name='stars',
            field=models.FloatField(default=5.0),
        ),
    ]
