# Generated by Django 4.2.5 on 2023-09-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_computer_instocks_computer_is_onsale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.CharField(choices=[('Windows11', 'Windows11'), ('Windows10', 'Windows10'), ('Non', 'Non'), ('Ubuntu', 'Ubuntu'), ('Archlinux', 'Archlinux')], default='Windows11', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='case',
            field=models.CharField(choices=[('Mini-itx', 'Mini-Itx'), ('Micro-atx', 'Micro-Atx'), ('Atx', 'Atx')], max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu_brand',
            field=models.CharField(choices=[('Reda', 'Reda'), ('Bluei', 'Bluei')], default='Bluei', max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='display',
            field=models.CharField(choices=[('Ips', 'Ips'), ('Tn', 'Tn'), ('Va', 'Va'), ('Oled', 'Oled')], default='Ips', max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='gpu_brand',
            field=models.CharField(choices=[('Reda', 'Reda'), ('Bluei', 'Bluei'), ('Greenn', 'Greenn')], default='Greenn', max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(choices=[('4Gb', '4Gb'), ('8Gb', '8Gb'), ('16Gb', '16Gb'), ('32Gb', '32Gb'), ('64Gb', '64Gb')], default='16Gb', max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='refreshrate',
            field=models.CharField(choices=[('60Hz', '60Hz'), ('75Hz', '75Hz'), ('90Hz', '90Hz'), ('120Hz', '120Hz'), ('144Hz', '144Hz'), ('240Hz', '240Hz')], default='60Hz', max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='resolution',
            field=models.CharField(choices=[('768P', '768P'), ('1080P', '1080P'), ('1440P', '1440P'), ('4K', '4K')], default='1080p', max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='size',
            field=models.CharField(choices=[('14"', '14"'), ('15.6"', '15.6"'), ('16"', '16"'), ('24"', '24"'), ('27"', '27"'), ('32"', '32"')], default='15.6"', max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage_type',
            field=models.CharField(choices=[('Hdd', 'Hdd'), ('Ssd', 'Ssd')], default='Ssd', max_length=10),
        ),
    ]
