# Generated by Django 4.2.5 on 2023-09-20 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_computer_color_alter_computer_storage_smartphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='og_price',
            field=models.IntegerField(default=8500),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.IntegerField(default=7900),
        ),
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='model_img/headphones/')),
                ('color', models.CharField(default='Black', max_length=100)),
                ('is_instock', models.BooleanField(default=True)),
                ('instocks', models.IntegerField(default=100)),
                ('is_onsale', models.BooleanField(default=True)),
                ('og_price', models.IntegerField(default=8500)),
                ('price', models.IntegerField(default=7900)),
                ('stars', models.FloatField(default=5.0)),
                ('is_recommend', models.BooleanField(default=False)),
                ('is_bluetooth', models.BooleanField(default=True)),
                ('is_waterproof', models.BooleanField(default=False)),
                ('has_noisecancelling', models.BooleanField(default=True)),
                ('has_microphone', models.BooleanField(default=True)),
                ('headphonetype', models.CharField(choices=[('Opened-back-on-ear', 'Opened-Back-On-Ear'), ('Closed-back-on-ear', 'Closed-Back-On-Ear'), ('Opened-back-over-ear', 'Opened-Back-Over-Ear'), ('Closed-back-over-ear', 'Closed-Back-Over-Ear'), ('In-ear', 'In-Ear')], default='Closed-back-over-ear', max_length=50)),
                ('port', models.CharField(choices=[('Usb', 'Usb'), ('Usb-c', 'Usb-C'), ('Aux3.5', 'Aux3.5')], default='Usb-c', max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
            ],
        ),
    ]
