# Generated by Django 4.2.5 on 2023-09-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_headphone_og_price_alter_headphone_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headphone',
            old_name='headphonetype',
            new_name='headphone_type',
        ),
        migrations.AddField(
            model_name='headphone',
            name='frequency_response',
            field=models.CharField(choices=[('20Hz-20khz', '20Hz-20Khz'), ('10Hz-24khz', '10Hz-24Khz'), ('40Hz-6800hz', '40Hz-6800Hz'), ('4Hz-40khz', '4Hz-40Khz')], default='', max_length=50),
        ),
    ]
