# Generated by Django 4.2.5 on 2023-09-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_headphonetype_headphone_headphone_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='back_camera',
            field=models.CharField(choices=[('10Mp', '10Mp'), ('12Mp', '12Mp'), ('32Mp', '32Mp'), ('50Mp', '50Mp')], default='32Mp', max_length=10),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='front_camera',
            field=models.CharField(choices=[('6Mp', '6Mp'), ('8Mp', '8Mp'), ('10Mp', '10Mp'), ('12Mp', '12Mp'), ('32Mp', '32Mp')], default='10Mp', max_length=10),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='os',
            field=models.CharField(choices=[('Android10', 'Android10'), ('Android11', 'Android11'), ('Android12', 'Android12'), ('Android13', 'Android13')], default='Android13', max_length=10),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sim',
            field=models.CharField(choices=[('1Sim', '1Sim'), ('2Sim', '2Sim')], default='1Sim', max_length=10),
        ),
    ]
