# Generated by Django 4.2.5 on 2023-09-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_smartphone_back_camera_smartphone_front_camera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='instocks',
            new_name='in_stocks',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='is_instock',
            new_name='is_in_stock',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='is_onsale',
            new_name='is_on_sale',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='refreshrate',
            new_name='refresh_rate',
        ),
        migrations.RenameField(
            model_name='headphone',
            old_name='has_noisecancelling',
            new_name='has_noise_cancelling',
        ),
        migrations.RenameField(
            model_name='headphone',
            old_name='instocks',
            new_name='in_stocks',
        ),
        migrations.RenameField(
            model_name='headphone',
            old_name='is_instock',
            new_name='is_in_stock',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='instocks',
            new_name='in_stocks',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='is_instock',
            new_name='is_in_stock',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='is_onsale',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='refreshrate',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='is_on_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='refresh_rate',
            field=models.CharField(blank=True, choices=[('60Hz', '60Hz'), ('75Hz', '75Hz'), ('90Hz', '90Hz'), ('120Hz', '120Hz'), ('144Hz', '144Hz'), ('240Hz', '240Hz')], default='90Hz', max_length=10),
        ),
    ]
