# Generated by Django 4.2.5 on 2023-09-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_instocks_computer_in_stocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphone',
            name='frequency_response',
            field=models.CharField(choices=[('20Hz-20khz', '20Hz-20Khz'), ('10Hz-24khz', '10Hz-24Khz'), ('40Hz-6800hz', '40Hz-6800Hz'), ('4Hz-40khz', '4Hz-40Khz')], default='20Hz-20khz', max_length=50),
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='model_img/cloths/')),
                ('color', models.CharField(default='White', max_length=100)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('in_stocks', models.IntegerField(default=100)),
                ('is_onsale', models.BooleanField(default=True)),
                ('og_price', models.IntegerField(default=1500)),
                ('price', models.IntegerField(default=900)),
                ('stars', models.FloatField(default=5.0)),
                ('is_recommend', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=10)),
                ('cloth_type', models.CharField(choices=[('T-shirt', 'T-Shirt'), ('Sleeveless-shirt', 'Sleeveless-Shirt'), ('Sweatshirt', 'Sweatshirt'), ('Hoody', 'Hoody'), ('Dress-shirt', 'Dress-Shirt')], default='T-shirt', max_length=50)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XXL', 'Xxl')], default='S', max_length=5)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
            ],
        ),
    ]
