# Generated by Django 4.2.5 on 2023-09-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_headphone_frequency_response_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('Xl', 'Xl'), ('Xxl', 'Xxl')], default='S', max_length=5),
        ),
    ]
