# Generated by Django 4.2.5 on 2023-09-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_computer_case_alter_computer_display_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='is_onsale',
            new_name='is_on_sale',
        ),
        migrations.RenameField(
            model_name='headphone',
            old_name='is_onsale',
            new_name='is_on_sale',
        ),
    ]
