# Generated by Django 5.1.7 on 2025-03-13 10:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='static/img/brands/')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='static/img/categories/')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('filter_field', models.TextField(blank=True, default='')),
                ('detail_field', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='static/img/products/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('progress', 'Progress'), ('confirm', 'Confirm'), ('delivery', 'Delivery'), ('done', 'Done')], max_length=10)),
                ('shipping_address', models.TextField(blank=True, default='')),
                ('billing_address', models.TextField(blank=True, default='')),
                ('total_amount', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order_products',
            field=models.ManyToManyField(to='ecommerce.orderproduct'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='static/img/products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('short_name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=250)),
                ('original_price', models.FloatField(default=100)),
                ('current_price', models.FloatField(default=100)),
                ('available_quantity', models.IntegerField(default=100)),
                ('theme', models.CharField(blank=True, default='', max_length=100)),
                ('cpu', models.CharField(blank=True, default='', max_length=100)),
                ('cpu_brand', models.CharField(blank=True, default='', max_length=20)),
                ('gpu', models.CharField(blank=True, default='', max_length=100)),
                ('gpu_brand', models.CharField(blank=True, default='', max_length=20)),
                ('ram', models.CharField(blank=True, default='', max_length=20)),
                ('bus', models.IntegerField(blank=True, default=0)),
                ('storage', models.CharField(blank=True, default='', max_length=20)),
                ('storage_type', models.CharField(blank=True, choices=[('hdd', 'HDD'), ('ssd', 'SSD')], max_length=5)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('resolution', models.CharField(blank=True, default='', max_length=20)),
                ('refresh_rate', models.IntegerField(blank=True, default=0.0)),
                ('size', models.FloatField(blank=True, default=0.0)),
                ('weight', models.FloatField(blank=True, default=0.0)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category')),
                ('carousel', models.ManyToManyField(blank=True, to='ecommerce.productcarousel')),
            ],
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(blank=True, default='', max_length=500)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('star', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(blank=True, to='ecommerce.userreview'),
        ),
    ]
